BERLIN_GAMES = [
    ("SuperMassive Blaze", "Acend", "GS A2"),
    ("Vision Strikers", "Paper Rex", "GS A1"),
    ("Vivo Keyd", "Envy", "GS B1"),
    ("KRU Esports", "ZETA DIVISION", "GS B2"),
    ("Gambit Esports", "Crazy Raccoon", "GS C1"),
    ("100 Thieves", "Havan Liberty", "GS C2"),
    ("Sentinels", "Bren Esports", "GS D1"),
    ("G2 Esports", "F4Q", "GS D2"),
    ("Vision Strikers", "SuperMassive Blaze", "GS A3"),
    ("Paper Rex", "Acend", "GS A4"),
    ("Envy", "KRU Esports", "GS B3"),
    ("Vivo Keyd", "ZETA DIVISION", "GS B4"),
    ("Gambit Esports", "100 Thieves", "GS C3"),
    ("Crazy Raccoon", "Havan Liberty", "GS C4"),
    ("Sentinels", "G2 Esports", "GS D3"),
    ("Bren Esports", "F4Q", "GS D4"),
    ("SuperMassive Blaze", "Acend", "GS A5"),
    ("KRU Esports", "Vivo Keyd", "GS B5"),
    ("Gambit Esports", "Havan Liberty", "GS C5"),
    ("G2 Esports", "F4Q", "GS D5"),
    ("Vision Strikers", "G2 Esports", "Quarters"),
    ("100 Thieves", "KRU Esports", "Quarters"),
    ("Envy", "Havan Liberty", "Quarters"),
    ("Sentinels", "Acend", "Quarters"),
    ("Vision Strikers", "100 Thieves", "Semis"),
    ("Envy", "Sentinels", "Semis"),
    ("Vision Strikers", "Sentinels", "Finals"),
]
